CREATE SCHEMA `ics_user` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `ics_user`.`web_user` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '主键',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `username` VARCHAR(45) UNIQUE NOT NULL COMMENT '用户名',
  `password` VARCHAR(45) NOT NULL COMMENT '密码',
  `password_salt` VARCHAR(45) NOT NULL COMMENT '加密密码',
  `token` VARCHAR(128) NOT NULL DEFAULT '' COMMENT '移动端TOKEN',
  `nickname` VARCHAR(45) UNIQUE NOT NULL DEFAULT '' COMMENT '昵称',
  `enable` TINYINT(1) NOT NULL DEFAULT 1 COMMENT '权限',
  PRIMARY KEY (`id`)
)  ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8 COMMENT='WEB端用户表';
